
# tap repositories and their packages

tap 'homebrew/core'
brew 'adns'
brew 'adr-tools'
brew 'adwaita-icon-theme'
brew 'ansible'
brew 'ant'
brew 'apr'
brew 'apr-util'
brew 'asciidoctor'
brew 'assimp'
brew 'atk'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'awslogs'
brew 'balena-cli'
brew 'bash'
brew 'bash-completion@2'
brew 'bat'
brew 'bdw-gc'
brew 'berkeley-db'
brew 'bfg'
brew 'boost'
brew 'brew-pip'
brew 'brotli'
brew 'c-ares'
brew 'cairo'
brew 'circleci'
brew 'cmake'
brew 'coreutils'
brew 'ctop'
brew 'curl'
brew 'dbus'
brew 'direnv'
brew 'dive'
brew 'docker'
brew 'double-conversion'
brew 'duf'
brew 'entr'
brew 'etcd'
brew 'exa'
brew 'exiftool'
brew 'expect'
brew 'fdupes'
brew 'fish'
brew 'fluxctl'
brew 'fontconfig'
brew 'foremost'
brew 'freetype'
brew 'fribidi'
brew 'fswatch'
brew 'gawk'
brew 'gcc'
brew 'gd'
brew 'gdb'
brew 'gdbm'
brew 'gdk-pixbuf'
brew 'gettext'
brew 'gh'
brew 'git'
brew 'git-extras'
brew 'git-flow'
brew 'git-lfs'
brew 'git-secret'
brew 'git-secrets'
brew 'glib'
brew 'gmime'
brew 'gmp'
brew 'gnu-sed'
brew 'gnupg'
brew 'gnuplot'
brew 'gnutls'
brew 'go'
brew 'go-jira'
brew 'gobject-introspection'
brew 'gpgme'
brew 'graphite2'
brew 'graphviz'
brew 'gsettings-desktop-schemas'
brew 'gtk+3'
brew 'gts'
brew 'guile'
brew 'harfbuzz'
brew 'helm'
brew 'helmfile'
brew 'hicolor-icon-theme'
brew 'highlight'
brew 'htop'
brew 'httpie'
brew 'hub'
brew 'hugo'
brew 'icu4c'
brew 'iftop'
brew 'imapfilter'
brew 'iperf'
brew 'isl'
brew 'jasper'
brew 'jemalloc'
brew 'jpeg'
brew 'jq'
brew 'k9s'
brew 'kind'
brew 'kops'
brew 'krew'
brew 'kubebuilder'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'kubeseal'
brew 'kubespy'
brew 'kustomize'
brew 'lazydocker'
brew 'lazygit'
brew 'libassuan'
brew 'libb2'
brew 'libcerf'
brew 'libepoxy'
brew 'libev'
brew 'libevent'
brew 'libffi'
brew 'libgcrypt'
brew 'libgpg-error'
brew 'libidn'
brew 'libidn2'
brew 'libksba'
brew 'libmetalink'
brew 'libmpc'
brew 'libpng'
brew 'libproxy'
brew 'libpthread-stubs'
brew 'librsvg'
brew 'libssh2'
brew 'libtasn1'
brew 'libtermkey'
brew 'libtiff'
brew 'libtool'
brew 'libunistring'
brew 'libusb'
brew 'libuv'
brew 'libvterm'
brew 'libx11'
brew 'libxau'
brew 'libxcb'
brew 'libxdmcp'
brew 'libxext'
brew 'libxfixes'
brew 'libxi'
brew 'libxinerama'
brew 'libxkbcommon'
brew 'libxml2'
brew 'libxrender'
brew 'libxtst'
brew 'libyaml'
brew 'libzip'
brew 'lmdb'
brew 'lua'
brew 'luajit'
brew 'luajit-openresty'
brew 'luarocks'
brew 'luv'
brew 'lz4'
brew 'lzo'
brew 'm-cli'
brew 'm4'
brew 'mas'
brew 'maven'
brew 'mercurial'
brew 'mitmproxy'
brew 'mpdecimal'
brew 'mpfr'
brew 'msgpack'
brew 'mu'
brew 'ncurses'
brew 'neomutt'
brew 'neovim'
brew 'netpbm'
brew 'nettle'
brew 'nghttp2'
brew 'nmap'
brew 'node'
brew 'node@10'
brew 'notmuch'
brew 'npth'
brew 'numpy'
brew 'octant'
brew 'offlineimap'
brew 'oniguruma'
brew 'openblas'
brew 'openjdk'
brew 'openldap'
brew 'openssl@1.1'
brew 'p11-kit'
brew 'p7zip'
brew 'packer'
brew 'pango'
brew 'pcre'
brew 'pcre2'
brew 'perl'
brew 'pinentry'
brew 'pipenv'
brew 'pixman'
brew 'pkg-config'
brew 'protobuf'
brew 'py3cairo'
brew 'pygobject3'
brew 'python@3.8'
brew 'python@3.9'
brew 'qt'
brew 'qt@5'
brew 'rbenv'
brew 'rbspy'
brew 'rclone'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'rtmpdump'
brew 'ruby'
brew 'ruby-build'
brew 'screen'
brew 'shellcheck'
brew 'skaffold'
brew 'sqlite'
brew 'subversion'
brew 'talloc'
brew 'tcl-tk'
brew 'tektoncd-cli'
brew 'teleport'
brew 'terraform'
brew 'terraform-docs'
brew 'terragrunt'
brew 'tflint'
brew 'tig'
brew 'tldr'
brew 'tmux'
brew 'tokyo-cabinet'
brew 'unbound'
brew 'unibilium'
brew 'utf8proc'
brew 'vault'
brew 'velero'
brew 'vim'
brew 'vnstat'
brew 'w3m'
brew 'watch'
brew 'webp'
brew 'wget'
brew 'xapian'
brew 'xdot'
brew 'xdotool'
brew 'xkeyboardconfig'
brew 'xmlstarlet'
brew 'xorgproto'
brew 'xz'
brew 'yarn'
brew 'yq'
brew 'z'
brew 'zlib'
brew 'zsh'
brew 'zsh-lovers'
brew 'zstd'

tap 'homebrew/cask-fonts'
cask 'font-consolas-for-powerline'
cask 'font-d2coding'
cask 'font-dashicons'
cask 'font-devicons'
cask 'font-fira-code'
cask 'font-fira-mono'
cask 'font-fontawesome'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-ionicons'
cask 'font-simple-line-icons'
cask 'font-source-code-pro'
cask 'font-ubuntu'

tap 'homebrew/cask-versions'
cask 'adoptopenjdk8'
cask 'docker-edge'
cask 'firefox-developer-edition'

tap 'homebrew/services'

tap 'homebrew/cask'
cask 'alfred'
cask 'balenaetcher'
cask 'bartender'
cask 'cakebrew'
cask 'cheatsheet'
cask 'cleanmymac'
cask 'dash'
cask 'dashlane'
cask 'datagrip'
cask 'dropbox'
cask 'electron-fiddle'
cask 'evernote'
cask 'fantastical'
cask 'fing'
cask 'franz'
cask 'gimp'
cask 'gitee'
cask 'github'
cask 'goland'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'google-drive'
cask 'google-drive-file-stream'
cask 'gpg-suite'
cask 'haptickey'
cask 'insomnia'
cask 'intellij-idea'
cask 'istat-menus'
cask 'iterm2'
cask 'kap'
cask 'lens'
cask 'linkliar'
cask 'multipass'
cask 'murus'
cask 'ngrok'
cask 'onyx'
cask 'paw'
cask 'postman'
cask 'pycharm'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlstephen'
cask 'quicklook-json'
cask 'remember-the-milk'
cask 'rubymine'
cask 'sequel-pro'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'suspicious-package'
cask 'telegram'
cask 'tunnelblick'
cask 'tuple'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'wireshark'
cask 'xquartz'
cask 'zeplin'
cask 'zoom'

tap 'boz/repo'
brew 'kail'

tap 'buildpacks/tap'
brew 'pack'

tap 'buo/cask-upgrade'

tap 'derailed/k9s'

tap 'github/gh'

tap 'hashicorp/tap'
brew 'waypoint'

tap 'helm/tap'
brew 'chart-releaser'

tap 'heroku/brew'
brew 'heroku'
brew 'heroku-node'

tap 'maxandersen/tap'

tap 'muesli/tap'

tap 'norwoodj/tap'
brew 'helm-docs'

tap 'rcmdnk/file'
brew 'brew-file'

tap 'tektoncd/tools'

tap 'ubuntu/microk8s'
brew 'microk8s'

tap 'wata727/tflint'

# Other Cask applications
cask 'flash-npapi'
cask 'flash-ppapi'
cask 'font-source-han-noto-cjk'
cask 'java'
cask 'station'

# App Store applications
mas 'Baby Monitor 3G (4.11.0)', id: 626137367
mas 'Disk Speed Test (3.3)', id: 425264550
mas 'Evernote Web Clipper (1.0.11)', id: 1481669779
mas 'Grammarly for Safari (9.30)', id: 1462114288
mas 'iMovie (10.2.3)', id: 408981434
mas 'Jira (128.1.0)', id: 1475897096
mas 'JustJoin (1.4.1)', id: 1514260034
mas 'Keynote (11.0.1)', id: 409183694
mas 'Kindle (1.31.0)', id: 405399194
mas 'Magnet (2.6.0)', id: 441258766
mas 'Numbers (11.0)', id: 409203825
mas 'Pages (11.0)', id: 409201541
mas 'Pomodoro-Tracker (19.5.15)', id: 1396146802
mas 'TweetDeck (3.18)', id: 485812721
mas 'YubiKey Personalization Tool (3.1.24)', id: 638161122
